- type: entity
  id: BasePlanetfallVendor
  name: So sigma
  description: Here you can tithe credits to the ringleader for equipment. Sweet, sweet privateering.
  components:
  - type: SpeakOnUIClosed
    pack: GenericVendGoodbyes
  - type: Transform
    anchored: true
    noRot: true
  - type: Clickable
  - type: InteractionOutline
  - type: Physics
    bodyType: Static

  - type: Sprite
    sprite: _Crescent/Structures/syndicatearmory.rsi
    layers:
    - state: "off"
      map: ["enum.VendingMachineVisualLayers.Base"]
    - state: "off"
      map: ["enum.VendingMachineVisualLayers.BaseUnshaded"]
      shader: unshaded
    - state: panel
      map: ["enum.WiresVisualLayers.MaintenancePanel"]
    - type: Tag
    tags:
    - Structure
      #    offState: off
      #    brokenState: broken
  - type: AmbientOnPowered
  - type: AmbientSound
    volume: -9
    range: 3
    enabled: false
    sound:
      path: /Audio/Ambience/Objects/vending_machine_hum.ogg


